name: Flask App Deployment

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Railway/Render
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} # For Railway
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }} # For Render
      run: |
        echo "Follow deployment instructions on Railway/Render dashboards."
